# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
#aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
#fog_directory: <%= ENV["FOG_DIRECTORY"] %>

development:
  secret_key_base: 62de2826115e57248bb49d39eba58ca33373fe195be0c77dd5341facafc297f9e140ddbddce4d85298afd07a5ccb3893868b916941279c29fd57b17a9c17394f
  secret_key: sk_test_hhnZgxUzpid4PweuND5kNXXE
  publishable_key: pk_test_87LayhWLhTKpfeY88G6tdHAb

test:
  secret_key_base: 8a72cd69545dfabe6f3b525ff32c131d5d2fcb721dfdca2f4208ac029cda3d5d0655cba0fe726f29c3185f401fa7c36de4aa9a74ae36fa642862597e84a2e08a
  secret_key: sk_test_hhnZgxUzpid4PweuND5kNXXE
  publishable_key: pk_test_87LayhWLhTKpfeY88G6tdHAb
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_key: <%= ENV['SECRET_KEY'] %>
  publishable_key: <%= ENV['PUBLISHABLE_KEY'] %>
